In [1]:
#imports
#numpy,pandas,scipy, math, matplotlib
import numpy as np
import pandas as pd
import scipy
from math import sqrt
import matplotlib.pyplot as plt

#estimators
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import linear_model

#model metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#cross validation
from sklearn.model_selection import train_test_split

In [2]:
#data
Credit = pd.read_csv('defaultofcreditcardclients.csv', header=1)
Credit.head()

ID  LIMITBAL  SEX  EDUCATION  MARRIAGE  AGE  PAYZERO  PAYTWO  PAYTHREE  \
0   1     20000    2          2         1   24        2       2        -1   
1   2    120000    2          2         2   26       -1       2         0   
2   3     90000    2          2         2   34        0       0         0   
3   4     50000    2          2         1   37        0       0         0   
4   5     50000    1          2         1   57       -1       0        -1   

   PAYFOUR  ...  BILLAMTFOUR  BILLAMTFIVE  BILLAMTSIX  PAYAMT0NE  PAYAMTTWO  \
0       -1  ...            0            0           0          0        689   
1        0  ...         3272         3455        3261          0       1000   
2        0  ...        14331        14948       15549       1518       1500   
3        0  ...        28314        28959       29547       2000       2019   
4        0  ...        20940        19146       19131       2000      36681   

   PAYAMTTHREE  PAYAMTFOUR  PAYFIVE.1  PAYAMTSIX  DPNM  
0            0           0          0          0     1  
1         1000        1000          0       2000     1  
2         1000        1000       1000       5000     0  
3         1200        1100       1069       1000     0  
4        10000        9000        689        679     0  

[5 rows x 25 columns]

In [3]:
Credit.dropna()

ID  LIMITBAL  SEX  EDUCATION  MARRIAGE  AGE  PAYZERO  PAYTWO  \
0          1     20000    2          2         1   24        2       2   
1          2    120000    2          2         2   26       -1       2   
2          3     90000    2          2         2   34        0       0   
3          4     50000    2          2         1   37        0       0   
4          5     50000    1          2         1   57       -1       0   
...      ...       ...  ...        ...       ...  ...      ...     ...   
29995  29996    220000    1          3         1   39        0       0   
29996  29997    150000    1          3         2   43       -1      -1   
29997  29998     30000    1          2         2   37        4       3   
29998  29999     80000    1          3         1   41        1      -1   
29999  30000     50000    1          2         1   46        0       0   

       PAYTHREE  PAYFOUR  ...  BILLAMTFOUR  BILLAMTFIVE  BILLAMTSIX  \
0            -1       -1  ...            0            0           0   
1             0        0  ...         3272         3455        3261   
2             0        0  ...        14331        14948       15549   
3             0        0  ...        28314        28959       29547   
4            -1        0  ...        20940        19146       19131   
...         ...      ...  ...          ...          ...         ...   
29995         0        0  ...        88004        31237       15980   
29996        -1       -1  ...         8979         5190           0   
29997         2       -1  ...        20878        20582       19357   
29998         0        0  ...        52774        11855       48944   
29999         0        0  ...        36535        32428       15313   

       PAYAMT0NE  PAYAMTTWO  PAYAMTTHREE  PAYAMTFOUR  PAYFIVE.1  PAYAMTSIX  \
0              0        689            0           0          0          0   
1              0       1000         1000        1000          0       2000   
2           1518       1500         1000        1000       1000       5000   
3           2000       2019         1200        1100       1069       1000   
4           2000      36681        10000        9000        689        679   
...          ...        ...          ...         ...        ...        ...   
29995       8500      20000         5003        3047       5000       1000   
29996       1837       3526         8998         129          0          0   
29997          0          0        22000        4200       2000       3100   
29998      85900       3409         1178        1926      52964       1804   
29999       2078       1800         1430        1000       1000       1000   

       DPNM  
0         1  
1         1  
2         0  
3         0  
4         0  
...     ...  
29995     0  
29996     0  
29997     1  
29998     1  
29999     1  

[30000 rows x 25 columns]

In [5]:
Credit.drop(['ID'], axis=1)

LIMITBAL  SEX  EDUCATION  MARRIAGE  AGE  PAYZERO  PAYTWO  PAYTHREE  \
0         20000    2          2         1   24        2       2        -1   
1        120000    2          2         2   26       -1       2         0   
2         90000    2          2         2   34        0       0         0   
3         50000    2          2         1   37        0       0         0   
4         50000    1          2         1   57       -1       0        -1   
...         ...  ...        ...       ...  ...      ...     ...       ...   
29995    220000    1          3         1   39        0       0         0   
29996    150000    1          3         2   43       -1      -1        -1   
29997     30000    1          2         2   37        4       3         2   
29998     80000    1          3         1   41        1      -1         0   
29999     50000    1          2         1   46        0       0         0   

       PAYFOUR  PAYFIVE  ...  BILLAMTFOUR  BILLAMTFIVE  BILLAMTSIX  PAYAMT0NE  \
0           -1       -2  ...            0            0           0          0   
1            0        0  ...         3272         3455        3261          0   
2            0        0  ...        14331        14948       15549       1518   
3            0        0  ...        28314        28959       29547       2000   
4            0        0  ...        20940        19146       19131       2000   
...        ...      ...  ...          ...          ...         ...        ...   
29995        0        0  ...        88004        31237       15980       8500   
29996       -1        0  ...         8979         5190           0       1837   
29997       -1        0  ...        20878        20582       19357          0   
29998        0        0  ...        52774        11855       48944      85900   
29999        0        0  ...        36535        32428       15313       2078   

       PAYAMTTWO  PAYAMTTHREE  PAYAMTFOUR  PAYFIVE.1  PAYAMTSIX  DPNM  
0            689            0           0          0          0     1  
1           1000         1000        1000          0       2000     1  
2           1500         1000        1000       1000       5000     0  
3           2019         1200        1100       1069       1000     0  
4          36681        10000        9000        689        679     0  
...          ...          ...         ...        ...        ...   ...  
29995      20000         5003        3047       5000       1000     0  
29996       3526         8998         129          0          0     0  
29997          0        22000        4200       2000       3100     1  
29998       3409         1178        1926      52964       1804     1  
29999       1800         1430        1000       1000       1000     1  

[30000 rows x 24 columns]

In [15]:
#features
features = Credit.iloc[:,1:24]
print('Summary of feature sample')
features.head()

Summary of feature sample


LIMITBAL  SEX  EDUCATION  MARRIAGE  AGE  PAYZERO  PAYTWO  PAYTHREE  \
0     20000    2          2         1   24        2       2        -1   
1    120000    2          2         2   26       -1       2         0   
2     90000    2          2         2   34        0       0         0   
3     50000    2          2         1   37        0       0         0   
4     50000    1          2         1   57       -1       0        -1   

   PAYFOUR  PAYFIVE  ...  BILLAMTTHREE  BILLAMTFOUR  BILLAMTFIVE  BILLAMTSIX  \
0       -1       -2  ...           689            0            0           0   
1        0        0  ...          2682         3272         3455        3261   
2        0        0  ...         13559        14331        14948       15549   
3        0        0  ...         49291        28314        28959       29547   
4        0        0  ...         35835        20940        19146       19131   

   PAYAMT0NE  PAYAMTTWO  PAYAMTTHREE  PAYAMTFOUR  PAYFIVE.1  PAYAMTSIX  
0          0        689            0           0          0          0  
1          0       1000         1000        1000          0       2000  
2       1518       1500         1000        1000       1000       5000  
3       2000       2019         1200        1100       1069       1000  
4       2000      36681        10000        9000        689        679  

[5 rows x 23 columns]

In [16]:
#dependent variable
depVar = Credit['DPNM']

In [17]:
#Training Set (Feature Space: X Training)
X_train = (features[: 21000])
X_train.head()

LIMITBAL  SEX  EDUCATION  MARRIAGE  AGE  PAYZERO  PAYTWO  PAYTHREE  \
0     20000    2          2         1   24        2       2        -1   
1    120000    2          2         2   26       -1       2         0   
2     90000    2          2         2   34        0       0         0   
3     50000    2          2         1   37        0       0         0   
4     50000    1          2         1   57       -1       0        -1   

   PAYFOUR  PAYFIVE  ...  BILLAMTTHREE  BILLAMTFOUR  BILLAMTFIVE  BILLAMTSIX  \
0       -1       -2  ...           689            0            0           0   
1        0        0  ...          2682         3272         3455        3261   
2        0        0  ...         13559        14331        14948       15549   
3        0        0  ...         49291        28314        28959       29547   
4        0        0  ...         35835        20940        19146       19131   

   PAYAMT0NE  PAYAMTTWO  PAYAMTTHREE  PAYAMTFOUR  PAYFIVE.1  PAYAMTSIX  
0          0        689            0           0          0          0  
1          0       1000         1000        1000          0       2000  
2       1518       1500         1000        1000       1000       5000  
3       2000       2019         1200        1100       1069       1000  
4       2000      36681        10000        9000        689        679  

[5 rows x 23 columns]

In [19]:
#Dependent Variable Training Set (y Training)
y_train = depVar[: 21000]
y_train_count = len(y_train.index)
print('The number of observations in the Y training set are:',str(y_train_count))
y_train.head()

The number of observations in the Y training set are: 21000


0    1
1    1
2    0
3    0
4    0
Name: DPNM, dtype: int64

In [18]:
#Testing Set (X Testing)
X_test = features[-9000:]
X_test_count = len(X_test.index)
print('The number of observations in the feature testing set is:',str(X_test_count))
print(X_test.head())

The number of observations in the feature testing set is: 9000
       LIMITBAL  SEX  EDUCATION  MARRIAGE  AGE  PAYZERO  PAYTWO  PAYTHREE  \
21000     30000    1          2         1   36        1      -1        -1   
21001    280000    1          3         1   40        2       0         0   
21002    260000    1          2         1   37        0       0         0   
21003    200000    1          2         2   32        2       0         0   
21004     80000    1          2         2   32        2       0         0   

       PAYFOUR  PAYFIVE  ...  BILLAMTTHREE  BILLAMTFOUR  BILLAMTFIVE  \
21000       -1        0  ...             0         1170          780   
21001        0        0  ...        188411       191291       189029   
21002        0        0  ...         21557        23186        14117   
21003        0       -2  ...         81890            0            0   
21004        0        0  ...         67253        67352        74448   

       BILLAMTSIX  PAYAMT0NE  PAYAMTTWO  

In [20]:
#Ground Truth (y_test) 
y_test = depVar[-9000:]
y_test_count = len(y_test.index)
print('The number of observations in the Y training set are:',str(y_test_count))
y_test.head()

The number of observations in the Y training set are: 9000


21000    0
21001    1
21002    0
21003    1
21004    1
Name: DPNM, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train)

In [23]:
X_train.shape, X_test.shape

((15750, 23), (5250, 23))

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train)
X_train.shape, X_test.shape

((11812, 23), (3938, 23))

In [27]:
x = features

In [30]:
#dependent variable
y = Credit['DPNM']

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [37]:
#KNN Model
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [35]:
y_pred = classifier.predict(X_test)

In [36]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6402  585]
 [1297  716]]
              precision    recall  f1-score   support

           0       0.83      0.92      0.87      6987
           1       0.55      0.36      0.43      2013

    accuracy                           0.79      9000
   macro avg       0.69      0.64      0.65      9000
weighted avg       0.77      0.79      0.77      9000



In [38]:
#KNN Model
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=10, leaf_size = 25)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=25, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [39]:
y_pred = classifier.predict(X_test)

In [40]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6651  336]
 [1384  629]]
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      6987
           1       0.65      0.31      0.42      2013

    accuracy                           0.81      9000
   macro avg       0.74      0.63      0.65      9000
weighted avg       0.79      0.81      0.78      9000



In [41]:
#KNN Model
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=15, leaf_size = 20)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=20, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=15, p=2,
                     weights='uniform')

In [42]:
y_pred = classifier.predict(X_test)

In [43]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6604  383]
 [1319  694]]
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      6987
           1       0.64      0.34      0.45      2013

    accuracy                           0.81      9000
   macro avg       0.74      0.64      0.67      9000
weighted avg       0.79      0.81      0.79      9000



In [44]:
#KNN Model
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=10, leaf_size = 20)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=20, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [45]:
y_pred = classifier.predict(X_test)

In [46]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6651  336]
 [1384  629]]
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      6987
           1       0.65      0.31      0.42      2013

    accuracy                           0.81      9000
   macro avg       0.74      0.63      0.65      9000
weighted avg       0.79      0.81      0.78      9000



In [47]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [48]:
y_pred = svclassifier.predict(X_test)

In [49]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[6795  192]
 [1514  499]]
              precision    recall  f1-score   support

           0       0.82      0.97      0.89      6987
           1       0.72      0.25      0.37      2013

    accuracy                           0.81      9000
   macro avg       0.77      0.61      0.63      9000
weighted avg       0.80      0.81      0.77      9000



In [50]:
from sklearn.svm import SVC
svclassifier = SVC(cache_size = 150, C= 2.0)
svclassifier.fit(X_train, y_train)

SVC(C=2.0, cache_size=150, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [51]:
y_pred = svclassifier.predict(X_test)

In [52]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[6691  296]
 [1290  723]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.89      6987
           1       0.71      0.36      0.48      2013

    accuracy                           0.82      9000
   macro avg       0.77      0.66      0.69      9000
weighted avg       0.81      0.82      0.80      9000



In [53]:
from sklearn.svm import SVC
svclassifier = SVC(cache_size = 100, C= 3.0)
svclassifier.fit(X_train, y_train)

SVC(C=3.0, cache_size=100, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [54]:
y_pred = svclassifier.predict(X_test)

In [55]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[6675  312]
 [1285  728]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.89      6987
           1       0.70      0.36      0.48      2013

    accuracy                           0.82      9000
   macro avg       0.77      0.66      0.69      9000
weighted avg       0.81      0.82      0.80      9000



In [56]:
from sklearn.svm import SVC
svclassifier = SVC(cache_size = 50, C= 5.0)
svclassifier.fit(X_train, y_train)

SVC(C=5.0, cache_size=50, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [57]:
y_pred = svclassifier.predict(X_test)

In [58]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[6668  319]
 [1288  725]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      6987
           1       0.69      0.36      0.47      2013

    accuracy                           0.82      9000
   macro avg       0.77      0.66      0.68      9000
weighted avg       0.81      0.82      0.80      9000



In [59]:
from sklearn.svm import SVC
svclassifier = SVC(cache_size = 50, C= 5.0, degree=2)
svclassifier.fit(X_train, y_train)

SVC(C=5.0, cache_size=50, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=2, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [60]:
y_pred = svclassifier.predict(X_test)

In [61]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[6668  319]
 [1288  725]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      6987
           1       0.69      0.36      0.47      2013

    accuracy                           0.82      9000
   macro avg       0.77      0.66      0.68      9000
weighted avg       0.81      0.82      0.80      9000



In [62]:
from sklearn.svm import SVC
svclassifier = SVC(cache_size = 500, C= 1.0, degree=4)
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=500, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=4, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [63]:
y_pred = svclassifier.predict(X_test)

In [64]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[6694  293]
 [1294  719]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.89      6987
           1       0.71      0.36      0.48      2013

    accuracy                           0.82      9000
   macro avg       0.77      0.66      0.68      9000
weighted avg       0.81      0.82      0.80      9000



In [65]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [66]:
from sklearn.svm import SVC
svclassifier = SVC(cache_size = 200, C= 2.0, degree=3)
svclassifier.fit(X_train, y_train)

SVC(C=2.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [67]:
y_pred = svclassifier.predict(X_test)

In [68]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[6691  296]
 [1290  723]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.89      6987
           1       0.71      0.36      0.48      2013

    accuracy                           0.82      9000
   macro avg       0.77      0.66      0.69      9000
weighted avg       0.81      0.82      0.80      9000



In [69]:
from sklearn.svm import SVC
svclassifier = SVC(cache_size = 1000, C= 0.5, degree=10)
svclassifier.fit(X_train, y_train)

SVC(C=0.5, cache_size=1000, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=10, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [70]:
y_pred = svclassifier.predict(X_test)

In [71]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[6694  293]
 [1303  710]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.89      6987
           1       0.71      0.35      0.47      2013

    accuracy                           0.82      9000
   macro avg       0.77      0.66      0.68      9000
weighted avg       0.81      0.82      0.80      9000



In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [73]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [74]:
y_pred = classifier.predict(X_test)

In [75]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[5634 1353]
 [1162  851]]
              precision    recall  f1-score   support

           0       0.83      0.81      0.82      6987
           1       0.39      0.42      0.40      2013

    accuracy                           0.72      9000
   macro avg       0.61      0.61      0.61      9000
weighted avg       0.73      0.72      0.72      9000



In [76]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(min_samples_leaf=10, min_samples_split=5)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=10, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [77]:
y_pred = classifier.predict(X_test)

In [78]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6189  798]
 [1268  745]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      6987
           1       0.48      0.37      0.42      2013

    accuracy                           0.77      9000
   macro avg       0.66      0.63      0.64      9000
weighted avg       0.75      0.77      0.76      9000



In [79]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(min_samples_leaf=15, min_samples_split=20)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=15, min_samples_split=20,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [80]:
y_pred = classifier.predict(X_test)

In [81]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6317  670]
 [1244  769]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      6987
           1       0.53      0.38      0.45      2013

    accuracy                           0.79      9000
   macro avg       0.68      0.64      0.66      9000
weighted avg       0.77      0.79      0.77      9000



In [82]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(min_samples_leaf=30, min_samples_split=50)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=30, min_samples_split=50,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [83]:
y_pred = classifier.predict(X_test)

In [84]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6550  437]
 [1273  740]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.88      6987
           1       0.63      0.37      0.46      2013

    accuracy                           0.81      9000
   macro avg       0.73      0.65      0.67      9000
weighted avg       0.79      0.81      0.79      9000



In [85]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(min_samples_leaf=100, min_samples_split=80)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=100, min_samples_split=80,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [86]:
y_pred = classifier.predict(X_test)

In [87]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6651  336]
 [1268  745]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      6987
           1       0.69      0.37      0.48      2013

    accuracy                           0.82      9000
   macro avg       0.76      0.66      0.69      9000
weighted avg       0.81      0.82      0.80      9000



In [88]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(min_samples_leaf=200, min_samples_split=110)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=200, min_samples_split=110,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [89]:
y_pred = classifier.predict(X_test)

In [90]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6649  338]
 [1252  761]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      6987
           1       0.69      0.38      0.49      2013

    accuracy                           0.82      9000
   macro avg       0.77      0.66      0.69      9000
weighted avg       0.81      0.82      0.80      9000



In [92]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(min_samples_leaf=200, min_samples_split=110, min_weight_fraction_leaf=0.5)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=200, min_samples_split=110,
                       min_weight_fraction_leaf=0.5, presort=False,
                       random_state=None, splitter='best')

In [93]:
y_pred = classifier.predict(X_test)

In [94]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6987    0]
 [2013    0]]
              precision    recall  f1-score   support

           0       0.78      1.00      0.87      6987
           1       0.00      0.00      0.00      2013

    accuracy                           0.78      9000
   macro avg       0.39      0.50      0.44      9000
weighted avg       0.60      0.78      0.68      9000



/Users/erichoneycutt/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [95]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(min_samples_leaf=250, min_samples_split=130, min_weight_fraction_leaf=0.0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=250, min_samples_split=130,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [96]:
y_pred = classifier.predict(X_test)

In [97]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6609  378]
 [1203  810]]
              precision    recall  f1-score   support

           0       0.85      0.95      0.89      6987
           1       0.68      0.40      0.51      2013

    accuracy                           0.82      9000
   macro avg       0.76      0.67      0.70      9000
weighted avg       0.81      0.82      0.81      9000



In [98]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=100)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=100, p=2,
                     weights='uniform')

In [99]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=100, leaf_size=45, p=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=45, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=100, p=5,
                     weights='uniform')

In [100]:
y_pred = classifier.predict(X_test)

In [101]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6706  281]
 [1418  595]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      6987
           1       0.68      0.30      0.41      2013

    accuracy                           0.81      9000
   macro avg       0.75      0.63      0.65      9000
weighted avg       0.79      0.81      0.78      9000



In [102]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(min_samples_leaf=200, min_samples_split=110)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=200, min_samples_split=110,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [103]:
y_pred = classifier.predict(X_test)

In [104]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6649  338]
 [1252  761]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      6987
           1       0.69      0.38      0.49      2013

    accuracy                           0.82      9000
   macro avg       0.77      0.66      0.69      9000
weighted avg       0.81      0.82      0.80      9000

